"""0.1 update func add

Revision ID: 082722d8bf1f
Revises: bf61145bb31e
Create Date: 2022-12-17 11:02:15.847987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082722d8bf1f'
down_revision = 'bf61145bb31e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
